import { body } from "express-validator";

export const createFlightValidator = [
  body("amadeusId").exists().trim(),
  body("ticketType").exists().trim(),
  body("price").exists().isNumeric(),
  body("travelClass").exists().trim(),
  body("bookedTickets").exists().isInt(),
  body("departureItinerary").exists().isObject(),
  body("departureItinerary.duration").exists().trim(),
  body("departureItinerary.totalDuration").exists().trim(),
  body("departureItinerary.totalDurationMinutes").exists().isInt(),
  body("departureItinerary.segments").isArray({ min: 1 }),
  body("departureItinerary.segments.*.id").exists().trim(),
  body("departureItinerary.segments.*.departureTime").exists().isISO8601(),
  body("departureItinerary.segments.*.arrivalTime").exists().isISO8601(),
  body("departureItinerary.segments.*.from").exists().trim(),
  body("departureItinerary.segments.*.to").exists().trim(),
  body("departureItinerary.segments.*.airLine").exists().trim(),
  body("departureItinerary.segments.*.airlineName").exists().trim(),
  body("departureItinerary.segments.*.flightNumber").exists().trim(),
  body("departureItinerary.segments.*.baggage").optional().trim(),
  body("departureItinerary.segments.*.cabinBags").optional().trim(),
  body("departureItinerary.segments.*.amenities").optional().trim(),
  body("departureItinerary.segments.*.travelClass").exists().trim(),
  body("departureItinerary.segments.*.stay").optional().trim(),
  body("departureItinerary.segments.*.segmentDuration").exists().trim(),
  body("departureItinerary.segments.*.segmentDurationMinutes").exists().isInt(),
  body("returnItinerary").optional().custom((value) => value === null || typeof value === 'object'),
];